# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# Diff drive controller configuration
diff_cont:
  ros__parameters:
    publish_rate: 50.0

    left_wheel_names: ["base_to_wheel_left"]
    right_wheel_names: ["base_to_wheel_right"]

    wheel_separation: 0.5
    wheel_radius: 0.1

    use_stamped_velocity: false

    # Position and velocity commands will be converted to velocity commands
    open_loop: false

    # Odometry 
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # Topic names
    cmd_vel_topic: cmd_vel
    odom_topic: odom
    publish_limited_velocity: true
    velocity_rolling_window_size: 10